/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicizehub.club.view;

/**
 *
 * @author budsagorn_ss
 */
public class FormEvaluations extends javax.swing.JFrame {

    /**
     * Creates new form FormEvaluations
     */
    public FormEvaluations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Question1 = new javax.swing.JPanel();
        Ques1 = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Q1_N2_1 = new javax.swing.JRadioButton();
        Q1_N2_2 = new javax.swing.JRadioButton();
        Q1_N2_5 = new javax.swing.JRadioButton();
        Q1_N2_3 = new javax.swing.JRadioButton();
        Q1_N2_4 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        Q1_N3_5 = new javax.swing.JRadioButton();
        Q1_N3_4 = new javax.swing.JRadioButton();
        Q1_N3_3 = new javax.swing.JRadioButton();
        Q1_N3_2 = new javax.swing.JRadioButton();
        Q1_N3_1 = new javax.swing.JRadioButton();
        Q1_N4_5 = new javax.swing.JRadioButton();
        Q1_N4_4 = new javax.swing.JRadioButton();
        Q1_N4_3 = new javax.swing.JRadioButton();
        Q1_N4_2 = new javax.swing.JRadioButton();
        Q1_N4_1 = new javax.swing.JRadioButton();
        Q1_N1_5 = new javax.swing.JRadioButton();
        Q1_N1_4 = new javax.swing.JRadioButton();
        Q1_N1_3 = new javax.swing.JRadioButton();
        Q1_N1_2 = new javax.swing.JRadioButton();
        Q1_N1_1 = new javax.swing.JRadioButton();
        Q1_N5_5 = new javax.swing.JRadioButton();
        Q1_N5_4 = new javax.swing.JRadioButton();
        Q1_N5_3 = new javax.swing.JRadioButton();
        Q1_N5_2 = new javax.swing.JRadioButton();
        Q1_N5_1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JPanel();
        Ques2 = new javax.swing.JPanel();
        q6 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();
        q9 = new javax.swing.JLabel();
        q10 = new javax.swing.JLabel();
        Q2_N1_5 = new javax.swing.JRadioButton();
        Q2_N1_4 = new javax.swing.JRadioButton();
        Q2_N1_3 = new javax.swing.JRadioButton();
        Q2_N1_2 = new javax.swing.JRadioButton();
        Q2_N1_1 = new javax.swing.JRadioButton();
        Q2_N2_1 = new javax.swing.JRadioButton();
        Q2_N2_2 = new javax.swing.JRadioButton();
        Q2_N2_3 = new javax.swing.JRadioButton();
        Q2_N2_4 = new javax.swing.JRadioButton();
        Q2_N2_5 = new javax.swing.JRadioButton();
        Q2_N3_5 = new javax.swing.JRadioButton();
        Q2_N3_4 = new javax.swing.JRadioButton();
        Q2_N3_3 = new javax.swing.JRadioButton();
        Q2_N3_2 = new javax.swing.JRadioButton();
        Q2_N3_1 = new javax.swing.JRadioButton();
        Q2_N4_1 = new javax.swing.JRadioButton();
        Q2_N4_2 = new javax.swing.JRadioButton();
        Q2_N4_4 = new javax.swing.JRadioButton();
        Q2_N4_3 = new javax.swing.JRadioButton();
        Q2_N4_5 = new javax.swing.JRadioButton();
        Q2_N5_5 = new javax.swing.JRadioButton();
        Q2_N5_4 = new javax.swing.JRadioButton();
        Q2_N5_3 = new javax.swing.JRadioButton();
        Q2_N5_2 = new javax.swing.JRadioButton();
        Q2_N5_1 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        Cancle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EventName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1195, 604));
        setResizable(false);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1172, 980));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setAutoscrolls(true);

        Question1.setBackground(new java.awt.Color(255, 255, 255));
        Question1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Question1.setForeground(new java.awt.Color(255, 255, 255));
        Question1.setAlignmentX(0.0F);
        Question1.setAlignmentY(0.0F);

        Ques1.setBackground(new java.awt.Color(255, 255, 255));

        q1.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q1.setText("1. ความเหมาะสมของการประชาสัมพันธ์กิจกรรม");

        q2.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q2.setText("2. ความเหมาะสมของรูปแบบการจัดกิจกรรม");

        q3.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q3.setText("3. ความเหมาะสมของสถานที่ที่ใช้จัดกิจกรรม");

        q4.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q4.setText("4. ความเหมาะสมของการประชาสัมพันธ์กิจกรรม");

        q5.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q5.setText("5. ความเหมาะสมของระยะเวลาในการดำเนินกิจกรรม");

        javax.swing.GroupLayout Ques1Layout = new javax.swing.GroupLayout(Ques1);
        Ques1.setLayout(Ques1Layout);
        Ques1Layout.setHorizontalGroup(
            Ques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ques1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        Ques1Layout.setVerticalGroup(
            Ques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ques1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        Q1_N2_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Q1_N2_1);
        Q1_N2_1.setText("1");

        Q1_N2_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Q1_N2_2);
        Q1_N2_2.setText("2");

        Q1_N2_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Q1_N2_5);
        Q1_N2_5.setText("5");
        Q1_N2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1_N2_5ActionPerformed(evt);
            }
        });

        Q1_N2_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Q1_N2_3);
        Q1_N2_3.setText("3");

        Q1_N2_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Q1_N2_4);
        Q1_N2_4.setText("4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addComponent(Q1_N2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1_N2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1_N2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1_N2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1_N2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1_N2_5)
                    .addComponent(Q1_N2_2)
                    .addComponent(Q1_N2_4)
                    .addComponent(Q1_N2_3)
                    .addComponent(Q1_N2_1))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        Q1_N3_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Q1_N3_5);
        Q1_N3_5.setText("5");
        Q1_N3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1_N3_5ActionPerformed(evt);
            }
        });

        Q1_N3_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Q1_N3_4);
        Q1_N3_4.setText("4");

        Q1_N3_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Q1_N3_3);
        Q1_N3_3.setText("3");

        Q1_N3_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Q1_N3_2);
        Q1_N3_2.setText("2");

        Q1_N3_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Q1_N3_1);
        Q1_N3_1.setText("1");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(Q1_N3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1_N3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1_N3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1_N3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1_N3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1_N3_5)
                    .addComponent(Q1_N3_2)
                    .addComponent(Q1_N3_4)
                    .addComponent(Q1_N3_3)
                    .addComponent(Q1_N3_1))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Q1_N4_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Q1_N4_5);
        Q1_N4_5.setText("5");
        Q1_N4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1_N4_5ActionPerformed(evt);
            }
        });

        Q1_N4_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Q1_N4_4);
        Q1_N4_4.setText("4");

        Q1_N4_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Q1_N4_3);
        Q1_N4_3.setText("3");

        Q1_N4_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Q1_N4_2);
        Q1_N4_2.setText("2");

        Q1_N4_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Q1_N4_1);
        Q1_N4_1.setText("1");

        Q1_N1_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Q1_N1_5);
        Q1_N1_5.setText("5");
        Q1_N1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1_N1_5ActionPerformed(evt);
            }
        });

        Q1_N1_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Q1_N1_4);
        Q1_N1_4.setText("4");

        Q1_N1_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Q1_N1_3);
        Q1_N1_3.setText("3");

        Q1_N1_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Q1_N1_2);
        Q1_N1_2.setText("2");

        Q1_N1_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Q1_N1_1);
        Q1_N1_1.setText("1");

        Q1_N5_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(Q1_N5_5);
        Q1_N5_5.setText("5");
        Q1_N5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1_N5_5ActionPerformed(evt);
            }
        });

        Q1_N5_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(Q1_N5_4);
        Q1_N5_4.setText("4");

        Q1_N5_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(Q1_N5_3);
        Q1_N5_3.setText("3");

        Q1_N5_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(Q1_N5_2);
        Q1_N5_2.setText("2");

        Q1_N5_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(Q1_N5_1);
        Q1_N5_1.setText("1");

        javax.swing.GroupLayout Question1Layout = new javax.swing.GroupLayout(Question1);
        Question1.setLayout(Question1Layout);
        Question1Layout.setHorizontalGroup(
            Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Question1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Ques1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Question1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Question1Layout.createSequentialGroup()
                                .addComponent(Q1_N1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Question1Layout.createSequentialGroup()
                                .addComponent(Q1_N5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Question1Layout.createSequentialGroup()
                                .addComponent(Q1_N4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q1_N4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1_N4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Question1Layout.setVerticalGroup(
            Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ques1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Question1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1_N1_5)
                    .addComponent(Q1_N1_2)
                    .addComponent(Q1_N1_4)
                    .addComponent(Q1_N1_3)
                    .addComponent(Q1_N1_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1_N4_5)
                    .addComponent(Q1_N4_2)
                    .addComponent(Q1_N4_4)
                    .addComponent(Q1_N4_3)
                    .addComponent(Q1_N4_1))
                .addGap(18, 18, 18)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1_N5_5)
                    .addComponent(Q1_N5_2)
                    .addComponent(Q1_N5_4)
                    .addComponent(Q1_N5_3)
                    .addComponent(Q1_N5_1))
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        jLabel1.setText("5-ดีมาก       4-ดี     3-ปานกลาง   2-พอใช้   1-ปรับปรุง");
        jLabel1.setToolTipText("");

        Question2.setBackground(new java.awt.Color(255, 255, 255));
        Question2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Ques2.setBackground(new java.awt.Color(255, 255, 255));

        q6.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q6.setText("1. ได้เรียนรู้การทำงานร่วมกับบุคคลอื่น");

        q7.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q7.setText("2. รู้จักการปรับตัวและชีวิตร่วมกับบุคคลอื่นมากขึ้น");

        q8.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q8.setText("3. ผู้เข้าร่วมกิจกรรมมีความรับผิดชอบต่อหน้าที่ที่ได้รับมอบหมาย");

        q9.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q9.setText("4. ผู้เข้าร่วมกิจกรรมได้รับความรู้จากการเข้าร่วมกิจกรรม");

        q10.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        q10.setText("5. ผู้เข้าร่วมกิจกรรมสามารถเอาความรู้ไปปรับใช้กับชีวิตประจำวันได้");

        javax.swing.GroupLayout Ques2Layout = new javax.swing.GroupLayout(Ques2);
        Ques2.setLayout(Ques2Layout);
        Ques2Layout.setHorizontalGroup(
            Ques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ques2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Ques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(q8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        Ques2Layout.setVerticalGroup(
            Ques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ques2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(q6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Q2_N1_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(Q2_N1_5);
        Q2_N1_5.setText("5");
        Q2_N1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2_N1_5ActionPerformed(evt);
            }
        });

        Q2_N1_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(Q2_N1_4);
        Q2_N1_4.setText("4");

        Q2_N1_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(Q2_N1_3);
        Q2_N1_3.setText("3");

        Q2_N1_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(Q2_N1_2);
        Q2_N1_2.setText("2");

        Q2_N1_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(Q2_N1_1);
        Q2_N1_1.setText("1");

        Q2_N2_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(Q2_N2_1);
        Q2_N2_1.setText("1");

        Q2_N2_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(Q2_N2_2);
        Q2_N2_2.setText("2");

        Q2_N2_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(Q2_N2_3);
        Q2_N2_3.setText("3");

        Q2_N2_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(Q2_N2_4);
        Q2_N2_4.setText("4");

        Q2_N2_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(Q2_N2_5);
        Q2_N2_5.setText("5");
        Q2_N2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2_N2_5ActionPerformed(evt);
            }
        });

        Q2_N3_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(Q2_N3_5);
        Q2_N3_5.setText("5");
        Q2_N3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2_N3_5ActionPerformed(evt);
            }
        });

        Q2_N3_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(Q2_N3_4);
        Q2_N3_4.setText("4");

        Q2_N3_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(Q2_N3_3);
        Q2_N3_3.setText("3");

        Q2_N3_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(Q2_N3_2);
        Q2_N3_2.setText("2");

        Q2_N3_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(Q2_N3_1);
        Q2_N3_1.setText("1");

        Q2_N4_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(Q2_N4_1);
        Q2_N4_1.setText("1");

        Q2_N4_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(Q2_N4_2);
        Q2_N4_2.setText("2");

        Q2_N4_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(Q2_N4_4);
        Q2_N4_4.setText("4");

        Q2_N4_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(Q2_N4_3);
        Q2_N4_3.setText("3");

        Q2_N4_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(Q2_N4_5);
        Q2_N4_5.setText("5");
        Q2_N4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2_N4_5ActionPerformed(evt);
            }
        });

        Q2_N5_5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(Q2_N5_5);
        Q2_N5_5.setText("5");
        Q2_N5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2_N5_5ActionPerformed(evt);
            }
        });

        Q2_N5_4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(Q2_N5_4);
        Q2_N5_4.setText("4");

        Q2_N5_3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(Q2_N5_3);
        Q2_N5_3.setText("3");

        Q2_N5_2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(Q2_N5_2);
        Q2_N5_2.setText("2");

        Q2_N5_1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(Q2_N5_1);
        Q2_N5_1.setText("1");

        javax.swing.GroupLayout Question2Layout = new javax.swing.GroupLayout(Question2);
        Question2.setLayout(Question2Layout);
        Question2Layout.setHorizontalGroup(
            Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Question2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Ques2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question2Layout.createSequentialGroup()
                        .addComponent(Q2_N4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Q2_N4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Q2_N4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q2_N4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q2_N4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Question2Layout.createSequentialGroup()
                            .addComponent(Q2_N3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Q2_N3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Q2_N3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Q2_N3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Q2_N3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Question2Layout.createSequentialGroup()
                                .addComponent(Q2_N2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q2_N2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q2_N2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q2_N2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q2_N2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Question2Layout.createSequentialGroup()
                                .addComponent(Q2_N1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q2_N1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Q2_N1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q2_N1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q2_N1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question2Layout.createSequentialGroup()
                        .addComponent(Q2_N5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Q2_N5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Q2_N5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q2_N5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q2_N5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        Question2Layout.setVerticalGroup(
            Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ques2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Question2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2_N1_5)
                    .addComponent(Q2_N1_2)
                    .addComponent(Q2_N1_4)
                    .addComponent(Q2_N1_3)
                    .addComponent(Q2_N1_1))
                .addGap(18, 18, 18)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2_N2_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Q2_N2_2)
                        .addComponent(Q2_N2_4)
                        .addComponent(Q2_N2_3)
                        .addComponent(Q2_N2_1)))
                .addGap(18, 18, 18)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2_N3_5)
                    .addComponent(Q2_N3_2)
                    .addComponent(Q2_N3_4)
                    .addComponent(Q2_N3_3)
                    .addComponent(Q2_N3_1))
                .addGap(18, 18, 18)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2_N4_5)
                    .addComponent(Q2_N4_2)
                    .addComponent(Q2_N4_4)
                    .addComponent(Q2_N4_3)
                    .addComponent(Q2_N4_1))
                .addGap(18, 18, 18)
                .addGroup(Question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2_N5_5)
                    .addComponent(Q2_N5_2)
                    .addComponent(Q2_N5_4)
                    .addComponent(Q2_N5_3)
                    .addComponent(Q2_N5_1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel3.setText("ข้อเสนอแนะ");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        Save.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        Save.setText("ยืนยัน");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Cancle.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        Cancle.setText("ยกเลิก");
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancle)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("ทักษะระหว่างบุคคลและความรับผิดชอบ");

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("ความคิดเห็นเกี่ยวกับการจัดกิจกรรม");

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1158, 60));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 28)); // NOI18N
        jLabel2.setText("ประเมินกิจกรรม");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        EventName.setText("ชื่อกิจกรรม");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(EventName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(EventName)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Question1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(411, 411, 411))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(801, 801, 801)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 37, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancleActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       
       //double Q1_N1_5 = Integer.parseInt(Q1_N1_5.getText());
          
        double x = 0.2; 
         
        int valueRadio1 = 0;
        int valueRadio2 = 0;
        int valueRadio3 = 0;
        int valueRadio4 = 0;
        int valueRadio5 = 0;
        int valueRadio6 = 0;
        int valueRadio7 = 0;
        int valueRadio8 = 0;
        int valueRadio9 = 0;
        int valueRadio10 = 0;             
               

//Q1
        //Num1
        if (Q1_N1_5.isSelected()) {
            valueRadio1 += 100;
        } else if (Q1_N1_4.isSelected()){
            valueRadio1 += 80;
        } else if (Q1_N1_3.isSelected()){
            valueRadio1 += 60;
        } else if (Q1_N1_2.isSelected()){
            valueRadio1 += 40;
        } else if (Q1_N1_1.isSelected()){
            valueRadio1 += 20;
        } else 
            valueRadio1 += 0;
    
        //Num2
         if (Q1_N2_5.isSelected()) {
            valueRadio2 += 100;
        } else if (Q1_N2_4.isSelected()){
            valueRadio2 += 80;
        } else if (Q1_N2_3.isSelected()){
            valueRadio2 += 60;
        } else if (Q1_N2_2.isSelected()){
            valueRadio2 += 40;
        } else if (Q1_N2_1.isSelected()){
            valueRadio2 += 20;
        } else {
            valueRadio2 += 0;
        }
        
        //Num3
         if (Q1_N3_5.isSelected()) {
            valueRadio3 += 100;
        } else if (Q1_N3_4.isSelected()){
            valueRadio3 += 80;
        } else if (Q1_N3_3.isSelected()){
            valueRadio3 += 60;
        } else if (Q1_N3_2.isSelected()){
            valueRadio3 += 40;
        } else if (Q1_N3_1.isSelected()){
            valueRadio3 += 20;
        } else {
            valueRadio3 += 0;
        }
         
        //Num4
         if (Q1_N4_5.isSelected()) {
            valueRadio4 += 100;
        } else if (Q1_N4_4.isSelected()){
            valueRadio4 += 80;
        } else if (Q1_N4_3.isSelected()){
            valueRadio4 += 60;
        } else if (Q1_N4_2.isSelected()){
            valueRadio4 += 40;
        } else if (Q1_N4_1.isSelected()){
            valueRadio4 += 20;
        } else {
            valueRadio4 += 0;
        }
         
        //Num5
         if (Q1_N5_5.isSelected()) {
            valueRadio5 += 100;
        } else if (Q1_N5_4.isSelected()){
            valueRadio5 += 80;
        } else if (Q1_N5_3.isSelected()){
            valueRadio5 += 60;
        } else if (Q1_N5_2.isSelected()){
            valueRadio5 += 40;
        } else if (Q1_N5_1.isSelected()){
            valueRadio5 += 20;
        } else {
            valueRadio5 += 0;
        }
         
//Q2
        //Num1
        if (Q2_N1_5.isSelected()) {
            valueRadio6 += 100;
        } else if (Q2_N1_4.isSelected()){
            valueRadio6 += 80;
        } else if (Q2_N1_3.isSelected()){
            valueRadio6 += 60;
        } else if (Q2_N1_2.isSelected()){
            valueRadio6 += 40;
        } else if (Q2_N1_1.isSelected()){
            valueRadio6 += 20;
        } else 
            valueRadio6 += 0;
    
        //Num2
         if (Q2_N2_5.isSelected()) {
            valueRadio7 += 100;
        } else if (Q2_N2_4.isSelected()){
            valueRadio7 += 80;
        } else if (Q2_N2_3.isSelected()){
            valueRadio7 += 60;
        } else if (Q2_N2_2.isSelected()){
            valueRadio7 += 40;
        } else if (Q2_N2_1.isSelected()){
            valueRadio7 += 20;
        } else {
            valueRadio7 += 0;
        }
        
        //Num3
         if (Q2_N3_5.isSelected()) {
            valueRadio8 += 100;
        } else if (Q2_N3_4.isSelected()){
            valueRadio8 += 80;
        } else if (Q2_N3_3.isSelected()){
            valueRadio8 += 60;
        } else if (Q2_N3_2.isSelected()){
            valueRadio8 += 40;
        } else if (Q2_N3_1.isSelected()){
            valueRadio8 += 20;
        } else {
            valueRadio8 += 0;
        }
         
        //Num4
         if (Q2_N4_5.isSelected()) {
            valueRadio9 += 100;
        } else if (Q2_N4_4.isSelected()){
            valueRadio9 += 80;
        } else if (Q2_N4_3.isSelected()){
            valueRadio9 += 60;
        } else if (Q2_N4_2.isSelected()){
            valueRadio9 += 40;
        } else if (Q2_N4_1.isSelected()){
            valueRadio9 += 20;
        } else {
            valueRadio9 += 0;
        }
         
        //Num5
         if (Q2_N5_5.isSelected()) {
            valueRadio10 += 100;
        } else if (Q2_N5_4.isSelected()){
            valueRadio10 += 80;
        } else if (Q2_N5_3.isSelected()){
            valueRadio10 += 60;
        } else if (Q2_N5_2.isSelected()){
            valueRadio10 += 40;
        } else if (Q2_N5_1.isSelected()){
            valueRadio10 += 20;
        } else {
            valueRadio10 += 0;
        } 
         
        // คิด percent แต่ละข้อ
        double percentNumber1=valueRadio1*x;
        double percentNumber2=valueRadio2*x;
        double percentNumber3=valueRadio3*x;
        double percentNumber4=valueRadio4*x;
        double percentNumber5=valueRadio5*x;
        double percentNumber6=valueRadio6*x;
        double percentNumber7=valueRadio7*x;
        double percentNumber8=valueRadio8*x;
        double percentNumber9=valueRadio9*x;
        double percentNumber10=valueRadio10*x;
        
        double percentQuestion1= percentNumber1+percentNumber2+percentNumber3+percentNumber4+percentNumber5;
        double percentQuestion2= percentNumber6+percentNumber7+percentNumber8+percentNumber9+percentNumber10;
        
         EventName.setText(Double.toString(percentQuestion1));
        
        
       
        
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void Q2_N5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2_N5_5ActionPerformed
      
    }//GEN-LAST:event_Q2_N5_5ActionPerformed

    private void Q2_N4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2_N4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2_N4_5ActionPerformed

    private void Q2_N3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2_N3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2_N3_5ActionPerformed

    private void Q2_N2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2_N2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2_N2_5ActionPerformed

    private void Q2_N1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2_N1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2_N1_5ActionPerformed

    private void Q1_N5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1_N5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1_N5_5ActionPerformed

    private void Q1_N1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1_N1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1_N1_5ActionPerformed

    private void Q1_N4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1_N4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1_N4_5ActionPerformed

    private void Q1_N3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1_N3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1_N3_5ActionPerformed

    private void Q1_N2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1_N2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1_N2_5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEvaluations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEvaluations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEvaluations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEvaluations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEvaluations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancle;
    private javax.swing.JLabel EventName;
    private javax.swing.JRadioButton Q1_N1_1;
    private javax.swing.JRadioButton Q1_N1_2;
    private javax.swing.JRadioButton Q1_N1_3;
    private javax.swing.JRadioButton Q1_N1_4;
    private javax.swing.JRadioButton Q1_N1_5;
    private javax.swing.JRadioButton Q1_N2_1;
    private javax.swing.JRadioButton Q1_N2_2;
    private javax.swing.JRadioButton Q1_N2_3;
    private javax.swing.JRadioButton Q1_N2_4;
    private javax.swing.JRadioButton Q1_N2_5;
    private javax.swing.JRadioButton Q1_N3_1;
    private javax.swing.JRadioButton Q1_N3_2;
    private javax.swing.JRadioButton Q1_N3_3;
    private javax.swing.JRadioButton Q1_N3_4;
    private javax.swing.JRadioButton Q1_N3_5;
    private javax.swing.JRadioButton Q1_N4_1;
    private javax.swing.JRadioButton Q1_N4_2;
    private javax.swing.JRadioButton Q1_N4_3;
    private javax.swing.JRadioButton Q1_N4_4;
    private javax.swing.JRadioButton Q1_N4_5;
    private javax.swing.JRadioButton Q1_N5_1;
    private javax.swing.JRadioButton Q1_N5_2;
    private javax.swing.JRadioButton Q1_N5_3;
    private javax.swing.JRadioButton Q1_N5_4;
    private javax.swing.JRadioButton Q1_N5_5;
    private javax.swing.JRadioButton Q2_N1_1;
    private javax.swing.JRadioButton Q2_N1_2;
    private javax.swing.JRadioButton Q2_N1_3;
    private javax.swing.JRadioButton Q2_N1_4;
    private javax.swing.JRadioButton Q2_N1_5;
    private javax.swing.JRadioButton Q2_N2_1;
    private javax.swing.JRadioButton Q2_N2_2;
    private javax.swing.JRadioButton Q2_N2_3;
    private javax.swing.JRadioButton Q2_N2_4;
    private javax.swing.JRadioButton Q2_N2_5;
    private javax.swing.JRadioButton Q2_N3_1;
    private javax.swing.JRadioButton Q2_N3_2;
    private javax.swing.JRadioButton Q2_N3_3;
    private javax.swing.JRadioButton Q2_N3_4;
    private javax.swing.JRadioButton Q2_N3_5;
    private javax.swing.JRadioButton Q2_N4_1;
    private javax.swing.JRadioButton Q2_N4_2;
    private javax.swing.JRadioButton Q2_N4_3;
    private javax.swing.JRadioButton Q2_N4_4;
    private javax.swing.JRadioButton Q2_N4_5;
    private javax.swing.JRadioButton Q2_N5_1;
    private javax.swing.JRadioButton Q2_N5_2;
    private javax.swing.JRadioButton Q2_N5_3;
    private javax.swing.JRadioButton Q2_N5_4;
    private javax.swing.JRadioButton Q2_N5_5;
    private javax.swing.JPanel Ques1;
    private javax.swing.JPanel Ques2;
    private javax.swing.JPanel Question1;
    private javax.swing.JPanel Question2;
    private javax.swing.JButton Save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel q9;
    // End of variables declaration//GEN-END:variables
}
